name: graphql_flutter_bloc_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  graphql:
    path: ../../packages/graphql
  cupertino_icons: ^0.1.2
  graphql_flutter_bloc: ^0.3.5-beta.1
  flutter_bloc: ^6.0.5
  gql: 0.12.2
  freezed_annotation: 0.12.0

  equatable: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  mockito: ^3.0.0

dependency_overrides:
  graphql:
    path: ../../packages/graphql

flutter:
  uses-material-design: true
