name: graphql
description: A stand-alone GraphQL client for Dart, bringing all the features from
  a modern GraphQL client to one easy to use package.
version: 3.0.1-beta.2
authors:
- Eus Dima <eus@zinoapp.com>
- Zino Hofmann <zino@zinoapp.com>
- Michael Joseph Rosenthal <rosenthalm93@gmail.com>
- TruongSinh Tran-Nguyen <i@truongsinh.pro>
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql
dependencies:
  meta: ^1.1.6
  path: ^1.6.2
  gql: ^0.12.0
  gql_exec: ^0.2.2
  gql_link: ^0.2.3
  quiver: '>=2.0.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.8.0+1
  mockito: ^4.0.0
  test: ^1.5.3
  test_coverage: ^0.3.0+1
environment:
  sdk: '>=2.6.0 <3.0.0'
