name: starwars_app
description: An example graphql_flutter application utilizing graphql_starwars_test_server

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: 
    path: ../../packages/graphql_flutter
  graphql:
    path: ../../packages/graphql
  graphql_starwars_test_server: ^0.1.0
  universal_platform: ^0.1.3
    # https://github.com/flutter/flutter/issues/36126#issuecomment-596215587

flutter:
  uses-material-design: true

dependency_overrides:
  graphql_flutter:
    path: ../../packages/graphql_flutter
  graphql:
    path: ../../packages/graphql
  graphql_starwars_test_server:
    path: /Users/mjr/Documents/code/libraries/angel-starwars-server

